<%@ Page Title="About Us" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeBehind="About.aspx.cs" Inherits="Storefront.About" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">

<!-- ############################# --> <!-- WIDGET EMBED CODE STARTS HERE --> <div> <h3 id="H1"><a href="http://www.cdc.gov/widgets/FluRSSAggregator/alt">Flu RSS Aggregator</a></h3> <p><br /> <!--[if!IE]><!--><object tabindex="0" id="Object1" data="http://www.cdc.gov/widgets/FluRSSAggregator/FluRSSAggregator.swf" width="170" height="335" type="application/x-shockwave-flash" title="Flu RSS Aggregator Widget"><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/> <param name="FlashVars" value="bg=ffffff"/><param name="pluginurl" value="http://get.adobe.com/flashplayer/"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/FluRSSAggregator/FluRSSAggregator.jpg" width="170" height="335" alt="Flu RSS Aggregator Widget. Flash Player 9 is required."/><br />Flu RSS Aggregator Widget. <br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><!--><![endif]-->     <!--[if IE]><object tabindex="0" id="widgetID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="170" height="335" title="widgetTitle"><param name="movie" value="http://www.cdc.gov/widgets/FluRSSAggregator/FluRSSAggregator.swf"/><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/><param name="FlashVars" value="bg=ffffff"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/FluRSSAggregator/FluRSSAggregator.jpg" width="170" height="335" alt="Flu RSS Aggregator Widget. Flash Player 9 is required."/><br />Flu RSS Aggregator Widget.<br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><![endif]-->     <a id="A1"></a></p></div> <!-- WIDGET EMBED CODE ENDS HERE --> <!-- ############################# -->

<!-- ############################# --> <!-- WIDGET EMBED CODE STARTS HERE --> <div> <h3 id="start-widget-focus"><a href="http://www.cdc.gov/tobacco/data_statistics/state_data/state_highlights/2012/index.htm">Tobacco Control State Highlights 2010</a></h3> <p><br /> <!--[if!IE]><!--><object tabindex="0" id="widgetID" data="http://www.cdc.gov/widgets/TobaccoMap/TobaccoMap.swf" width="556" height="404" type="application/x-shockwave-flash" title=" Tobacco Control State Highlights 2010 Widget"><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/> <param name="FlashVars" value="bg=ffffff"/><param name="pluginurl" value="http://get.adobe.com/flashplayer/"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/TobaccoMap/TobaccoMap.jpg" width="556" height="404" alt="Tobacco Control State Highlights 2010 Widget. Flash Player 9 is required."/><br />Tobacco Control State Highlights 2010 Widget. <br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><!--><![endif]-->     <!--[if IE]><object tabindex="0" id="widgetID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="556" height="404" title="widgetTitle"><param name="movie" value="http://www.cdc.gov/widgets/TobaccoMap/TobaccoMap.swf"/><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/><param name="FlashVars" value="bg=ffffff"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/TobaccoMap/TobaccoMap.jpg" width="556" height="404" alt="Tobacco Control State Highlights 2010 Widget. Flash Player 9 is required."/><br />Tobacco Control State Highlights 2010 Widget.<br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><![endif]-->     <a id="end-widget-focus"></a></p></div> <!-- WIDGET EMBED CODE ENDS HERE --> <!-- ############################# -->
<!-- ############################# --> <!-- WIDGET EMBED CODE STARTS HERE --> <div> <h3 id="H2"><a href="http://www.cdc.gov/widgets/PHIL/alt">Public Health Image Library Image of the Day Widget</a></h3> <p><br /> <!--[if!IE]><!--><object tabindex="0" id="Object2" data="http://www.cdc.gov/widgets/PHIL/Phil_TAN.swf" width="170" height="217" type="application/x-shockwave-flash" title="widgetTitle"><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/> <param name="FlashVars" value="bg=ffffff"/><param name="pluginurl" value="http://get.adobe.com/flashplayer/"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/PHIL/Phil_TAN.jpg" width="170" height="217" alt=" Public Health Image Library Image of the Day Widget. Flash Player 9 is required."/><br /> Public Health Image Library Image of the Day Widget. <br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><!--><![endif]-->     <!--[if IE]><object tabindex="0" id="widgetID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="170" height="217" title="widgetTitle"><param name="movie" value="http://www.cdc.gov/widgets/PHIL/Phil_TAN.swf"/><param name="quality" value="high"/><param name="AllowScriptAccess" value="always"/><param name="FlashVars" value="bg=ffffff"/><div style="width:auto"><img src="http://www.cdc.gov/widgets/PHIL/Phil_TAN.jpg" width="170" height="217" alt=" Public Health Image Library Image of the Day Widget. Flash Player 9 is required."/><br /> Public Health Image Library Image of the Day Widget. <br /><a href="http://get.adobe.com/flashplayer/">Flash Player 9 is required.</a></div></object><![endif]-->     <a id="A2"></a></div> <!-- WIDGET EMBED CODE ENDS HERE --> <!-- ############################# -->

</asp:Content>
